version: 2
updates:
  - package-ecosystem: "pip"
    directory: /
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 10
    rebase-strategy: auto

  - package-ecosystem: "github-actions"
    directories: ["/", ".github/actions/*"]
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 10
    rebase-strategy: auto
