#!/usr/bin/env python3
#
# Copyright (c) 2026 Circular Drive Initiative.
#
# This file is part of CDI Health.
# See https://github.com/circulardrives/cdi-grading-tool/ for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""
Generate the sample data behind the static dashboard demo (``VITE_DEMO=1``).

Run from the repository root (``scripts/build-demo.sh`` does this for you)::

    PYTHONPATH=src python scripts/generate_demo_data.py

Every drive comes from a smartctl-JSON fixture in the repo
(``src/cdi_health/mock_data`` and ``tests/fixtures/revert_standard``), is
anonymized (serials, WWN / EUI-64 / FGUID, vendor strings), and then goes
through the real pipeline: ``create_mock_device`` → the API's scoring
enrichment → the real API endpoints (machines, fleet, CSV, history, reports)
served in-process with FastAPI's TestClient. Grades and reasons are therefore
exactly what CDI Health produces for those drives.

Output (committed; regenerate after grading changes):

- ``dashboard/apps/web/src/demo/data/*.json``  API responses the demo serves
- ``dashboard/apps/web/src/demo/data/files/*`` pre-rendered report / CSV files

Serials are derived from a hash of bench + slot, and every timestamp is
fixed, so a rebuild with unchanged grading produces identical files.
"""

from __future__ import annotations

import copy
import hashlib
import json
import os
import re
import shutil
import sys
import tempfile
import time
import uuid
from collections.abc import Callable
from datetime import datetime, timedelta, timezone
from pathlib import Path
from types import SimpleNamespace
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

MOCK_DIR = REPO_ROOT / "src" / "cdi_health" / "mock_data"
REVERT_DIR = REPO_ROOT / "tests" / "fixtures" / "revert_standard"
OUT_DIR = REPO_ROOT / "dashboard" / "apps" / "web" / "src" / "demo" / "data"
FILES_DIR = OUT_DIR / "files"

# Everything happens "at" this moment; the demo shifts times to look recent.
GENERATED_AT = datetime(2026, 9, 25, 16, 0, 0, tzinfo=timezone.utc)
ID_NAMESPACE = uuid.UUID("5b1e6d2a-3c4f-4e8a-9d7b-0c1a2e3f4a5b")
COMMENT = (
    "Generated by scripts/generate_demo_data.py from repo fixtures through the real "
    "CDI Health grader (serials anonymized). Do not edit by hand; run scripts/build-demo.sh."
)

Mutator = Callable[[dict[str, Any]], None]


# ---------------------------------------------------------------------------
# Fixture tweaks (applied before grading, so the grade reflects them)
# ---------------------------------------------------------------------------


def security_locked(payload: dict[str, Any]) -> None:
    """ATA security lock engaged: CDI Health must report the drive UNGRADED (§15)."""
    payload["ata_security"] = {
        "state": 7,
        "string": "ENABLED, PW level HIGH, **LOCKED** [SEC4]",
        "enabled": True,
        "frozen": False,
        "locked": True,
    }


def recent_failed_segment(payload: dict[str, Any]) -> None:
    """Add a recent failed extended NVMe self-test (result 7: segment failed)."""
    hours = int((payload.get("power_on_time") or {}).get("hours") or 0)
    log = payload.setdefault("nvme_self_test_log", {})
    log.setdefault("current_self_test_operation", {"value": 0, "string": "No self-test in progress"})
    table = log.setdefault("table", [])
    table.insert(
        0,
        {
            "self_test_code": {"value": 2, "string": "Extended"},
            "self_test_result": {"value": 7, "string": "Completed: failed segments"},
            "segment": 2,
            "power_on_hours": max(hours - 30, 0),
        },
    )


def scsi_names(payload: dict[str, Any]) -> None:
    """Add the ``scsi_vendor`` / ``scsi_model_name`` keys smartctl 7.3+ emits (older fixtures lack them)."""
    if str((payload.get("device") or {}).get("protocol") or "").upper() != "SCSI":
        return
    vendor = str(payload.get("vendor") or "").strip()
    product = str(payload.get("product") or "").strip()
    if vendor and product:
        payload.setdefault("scsi_vendor", vendor)
        payload.setdefault("scsi_product", product)
        payload.setdefault("scsi_model_name", f"{vendor} {product}")
        if payload.get("revision"):
            payload.setdefault("scsi_revision", payload["revision"])


def older_by(hours: int) -> Mutator:
    """The same drive ``hours`` power-on hours earlier (for older saved scans)."""

    def mutate(payload: dict[str, Any]) -> None:
        pot = payload.get("power_on_time")
        if isinstance(pot, dict) and isinstance(pot.get("hours"), int):
            pot["hours"] = max(pot["hours"] - hours, 0)
        nvme = payload.get("nvme_smart_health_information_log")
        if isinstance(nvme, dict) and isinstance(nvme.get("power_on_hours"), int):
            nvme["power_on_hours"] = max(nvme["power_on_hours"] - hours, 0)
        for entry in (payload.get("ata_smart_attributes") or {}).get("table") or []:
            if entry.get("id") == 9 and isinstance(entry.get("raw"), dict):
                raw = entry["raw"]
                if isinstance(raw.get("value"), int):
                    raw["value"] = max(raw["value"] - hours, 0)
                    raw["string"] = str(raw["value"])

    return mutate


# ---------------------------------------------------------------------------
# Benches
# ---------------------------------------------------------------------------

# (slot, fixture path, mutators)
Drive = tuple[str, Path, tuple[Mutator, ...]]

BENCHES: list[dict[str, Any]] = [
    {
        "key": "bench-01",
        "address": "192.168.10.21:8844",
        "hostname": "bench-01.lab.example",
        "location": "Rack A · Server 1",
        "notes": "NVMe servers",
        "drives": [
            ("/dev/nvme0", MOCK_DIR / "nvme" / "KIOXIA_KCD81VUG6T40_healthy.json", ()),
            ("/dev/nvme1", MOCK_DIR / "nvme" / "FADU_DELTA_U_2_1_92TB_healthy.json", ()),
            ("/dev/nvme2", MOCK_DIR / "nvme" / "KCD81VUG6T40_healthy.json", ()),
            ("/dev/nvme3", MOCK_DIR / "nvme" / "KCD81VUG6T40_4_healthy.json", ()),
            ("/dev/nvme4", MOCK_DIR / "nvme" / "KCM61VUL3T20_healthy.json", ()),
            ("/dev/nvme5", MOCK_DIR / "nvme" / "SSDPE2KE032T8_healthy.json", ()),
            ("/dev/nvme6", MOCK_DIR / "nvme" / "SSDPE2KE032T8_3_healthy.json", ()),
            ("/dev/nvme7", MOCK_DIR / "nvme" / "SSDPF21Q800GB_healthy.json", (recent_failed_segment,)),
            ("/dev/nvme8", REVERT_DIR / "nvme_healthy_log_page_02h.json", ()),
            ("/dev/nvme9", REVERT_DIR / "nvme_critical_warning_high_wear.json", ()),
        ],
    },
    {
        "key": "bench-02",
        "address": "192.168.10.22:8844",
        "hostname": "bench-02.lab.example",
        "location": "Rack A · Server 2",
        "notes": "HDD chassis",
        "drives": [
            ("/dev/sda", MOCK_DIR / "ata" / "healthy_hdd.json", ()),
            ("/dev/sdb", REVERT_DIR / "ata_hdd_defects_band_b.json", ()),
            ("/dev/sdc", MOCK_DIR / "ata" / "high_reallocated.json", ()),
            ("/dev/sdd", MOCK_DIR / "ata" / "high_pending.json", ()),
            ("/dev/sde", REVERT_DIR / "ata_selftest_two_recent_failures.json", ()),
            ("/dev/sdf", REVERT_DIR / "ata_hdd_defects_band_f.json", ()),
            ("/dev/sdg", MOCK_DIR / "scsi" / "healthy_sas.json", ()),
            ("/dev/sdh", REVERT_DIR / "sas_enterprise_45k_poh_clean.json", ()),
            ("/dev/sdi", REVERT_DIR / "scsi_grown_defects_band_c.json", ()),
            ("/dev/sdj", REVERT_DIR / "report_1SHK383Z.json", ()),
            ("/dev/sdk", REVERT_DIR / "scsi_selftest_only_failure.json", ()),
            ("/dev/sdl", REVERT_DIR / "scsi_uncorrected_band_f.json", ()),
            ("/dev/sdm", REVERT_DIR / "report_ZAD2AX9T.json", ()),
            ("/dev/sdn", MOCK_DIR / "ata" / "healthy_hdd.json", (security_locked,)),
        ],
    },
    {
        "key": "bench-03",
        "address": "192.168.10.23:8844",
        "hostname": "bench-03.lab.example",
        "location": "Intake table",
        "notes": "Mixed intake",
        "drives": [
            ("/dev/sda", MOCK_DIR / "ata" / "MK000960GWSSD_healthy.json", ()),
            ("/dev/sdb", MOCK_DIR / "ata" / "SDSSDH3_512G_healthy.json", ()),
            ("/dev/sdc", REVERT_DIR / "ata_ssd_midlife_wear.json", ()),
            ("/dev/sdd", REVERT_DIR / "ata_ssd_end_of_life_wear.json", ()),
            ("/dev/sde", REVERT_DIR / "ata_consumer_25k_poh_clean.json", ()),
            ("/dev/sdf", REVERT_DIR / "ata_consumer_65k_poh_clean.json", ()),
            ("/dev/nvme0", MOCK_DIR / "nvme" / "SSDPEK1A118GA_healthy.json", ()),
            ("/dev/nvme1", MOCK_DIR / "nvme" / "Skhynix_PE6110_controller_failed.json", ()),
        ],
    },
]

# Latest scans (one per bench) plus one earlier scan per bench for drive history.
LATEST_SCAN_AT = {
    "bench-01": GENERATED_AT - timedelta(minutes=22),
    "bench-02": GENERATED_AT - timedelta(minutes=21),
    "bench-03": GENERATED_AT - timedelta(minutes=20),
}
EARLIER_SCANS = [
    # (bench, days before the latest scan, per-slot fixture swaps)
    ("bench-01", 7, {}),
    # A week ago /dev/sdb still had band-A defect counts (grade A → B since).
    ("bench-02", 7, {"/dev/sdb": REVERT_DIR / "ata_hdd_defects_band_a.json"}),
    ("bench-03", 2, {}),
]


# ---------------------------------------------------------------------------
# Anonymization
# ---------------------------------------------------------------------------

VENDOR_FOR_PRODUCT = (("ST", "SEAGATE"), ("HUC", "HGST"), ("NV", "SAMPLE"))


def _digest(*parts: str) -> bytes:
    return hashlib.sha256("|".join(parts).encode("utf-8")).digest()


def stable_serial(bench: str, slot: str, original: str) -> str:
    """Deterministic fake serial for one bench slot, shaped like ``original``."""
    template = original.strip().upper()
    if not re.fullmatch(r"[A-Z0-9-]{6,16}", template) or "MOCK" in template:
        template = "SSSDDDDDDSSD"
    digest = _digest("serial", bench, slot)
    letters = "ABCDEFGHJKLMNPQRSTUVWXYZ"
    out = []
    for index, char in enumerate(template):
        byte = digest[index % len(digest)] ^ index
        if char.isdigit():
            out.append(str(byte % 10))
        elif char.isalpha():
            out.append(letters[byte % len(letters)])
        else:
            out.append(char)
    serial = "".join(out)
    if serial == original.strip().upper():
        serial = "D" + serial[1:]
    return serial


def _stable_int(bench: str, slot: str, label: str, bits: int) -> int:
    return int.from_bytes(_digest(label, bench, slot)[:8], "big") % (1 << bits)


def _collect_serial_tokens(payload: dict[str, Any]) -> set[str]:
    """Every string in the fixture that is (or embeds) the drive serial."""
    tokens: set[str] = set()
    serial = str(payload.get("serial_number") or "").strip()
    if serial:
        tokens.add(serial)
    nvme_cli = payload.get("nvme_cli") or {}
    sn = str(((nvme_cli.get("id_ctrl") or {}).get("sn")) or "").strip()
    if sn:
        tokens.add(sn)
    for device in (nvme_cli.get("list") or {}).get("Devices") or []:
        value = str((device or {}).get("SerialNumber") or "").strip()
        if value:
            tokens.add(value)
    return {token for token in tokens if len(token) >= 4}


def _walk(obj: Any, fn: Callable[[str, Any], Any]) -> Any:
    if isinstance(obj, dict):
        return {key: fn(key, _walk(value, fn)) for key, value in obj.items()}
    if isinstance(obj, list):
        return [_walk(value, fn) for value in obj]
    return obj


def anonymize_fixture(payload: dict[str, Any], bench: str, slot: str) -> dict[str, Any]:
    """Copy of a smartctl fixture with serials/IDs replaced and the slot renamed."""
    from cdi_health.classes.mock_export import deep_replace_str

    data = copy.deepcopy(payload)
    original_serial = str(data.get("serial_number") or "")
    new_serial = stable_serial(bench, slot, original_serial or "SERIAL0000")
    for token in sorted(_collect_serial_tokens(data), key=len, reverse=True):
        data = deep_replace_str(data, token, new_serial)
    data["serial_number"] = new_serial

    def scrub_ids(key: str, value: Any) -> Any:
        if key == "wwn" and isinstance(value, dict):
            return {**value, "id": _stable_int(bench, slot, "wwn", 36)}
        if key == "eui64" and isinstance(value, dict):
            return {**value, "ext_id": _stable_int(bench, slot, "eui64", 40)}
        if key in ("fguid", "nguid") and isinstance(value, str) and value.strip("0-"):
            return str(uuid.UUID(bytes=_digest(key, bench, slot)[:16]))
        if key == "logical_unit_id" and isinstance(value, str):
            return f"0x5000c500{_stable_int(bench, slot, 'lu', 32):08x}"
        return value

    data = _walk(data, scrub_ids)

    # Fixture vendor placeholder → the product's real OEM (or a neutral name).
    def fix_vendor(text: str) -> str:
        match = re.match(r"^REVERT\s+(\S+)", text)
        if not match:
            return text
        product = match.group(1)
        vendor = next((v for prefix, v in VENDOR_FOR_PRODUCT if product.startswith(prefix)), "SAMPLE")
        return f"{vendor} {product}"

    for key in ("model_name", "model_family"):
        if isinstance(data.get(key), str):
            data[key] = fix_vendor(data[key])
    if data.get("vendor") == "REVERT":
        product = str(data.get("product") or "")
        data["vendor"] = next((v for prefix, v in VENDOR_FOR_PRODUCT if product.startswith(prefix)), "SAMPLE")

    # Put the drive in its demo slot (device.name drives the record's dut).
    old_name = str((data.get("device") or {}).get("name") or "")
    if old_name and old_name != slot:
        pattern = re.compile(re.escape(old_name) + r"(?!\d)")
        data = _walk(data, lambda _k, v: pattern.sub(slot, v) if isinstance(v, str) else v)
        data["device"]["name"] = slot
        if "info_name" in data["device"]:
            data["device"]["info_name"] = pattern.sub(slot, str(data["device"]["info_name"]))
    return data


# ---------------------------------------------------------------------------
# Real pipeline
# ---------------------------------------------------------------------------

# Bulky raw logs left out of saved-scan (history) snapshots to keep the demo small.
HISTORY_DROP_FIELDS = (
    "smartctl_json",
    "smart_attributes",
    "smart_self_tests",
    "nvme_self_test_log",
    "nvme_self_test_history",
    "nvme_error_information_log",
    "nvme_namespaces",
    "ocp_smart_log",
)


def grade_bench(bench: dict[str, Any], scanned_at: datetime, swaps: dict[str, Path] | None = None) -> dict[str, Any]:
    """Scan one bench's fixtures through the API's scoring path; returns a ScanResponse dict."""
    from cdi_health.api.services import _enrich_devices_with_scores, build_threshold_config, summarize_devices
    from cdi_health.classes.mock import create_mock_device

    swaps = swaps or {}
    raw_devices = []
    for slot, path, mutators in bench["drives"]:
        source = swaps.get(slot, path)
        payload = json.loads(source.read_text(encoding="utf-8"))
        payload = anonymize_fixture(payload, bench["key"], slot)
        scsi_names(payload)
        for mutate in mutators:
            mutate(payload)
        if scanned_at != LATEST_SCAN_AT[bench["key"]]:
            older_by(int((LATEST_SCAN_AT[bench["key"]] - scanned_at).total_seconds() // 3600))(payload)
        device = create_mock_device(mock_data=payload, device_id=slot).to_dict(pop=True)
        raw_devices.append({k: v for k, v in device.items() if not k.startswith("_")})

    threshold_config = build_threshold_config()
    devices = _enrich_devices_with_scores(raw_devices, threshold_config)
    stamp = scanned_at.isoformat(timespec="seconds")
    for device in devices:
        device["scan_timestamp"] = stamp
    return {
        "scanned_at": stamp,
        "grading_profile": threshold_config.grading_profile,
        "summary": summarize_devices(devices),
        "devices": devices,
    }


class _FrozenDatetime(datetime):
    @classmethod
    def now(cls, tz=None):  # noqa: D102
        frozen = GENERATED_AT
        return frozen.astimezone(tz) if tz else frozen.replace(tzinfo=None)


def _freeze_clock() -> None:
    """Pin every ``now()`` the API and reporter use, so output is reproducible."""
    import cdi_health.api.app as app_module
    import cdi_health.api.history as history_module
    import cdi_health.api.machines as machines_module
    import cdi_health.api.services as services_module
    import cdi_health.classes.reporter as reporter_module

    for module in (app_module, machines_module, services_module, reporter_module):
        module.datetime = _FrozenDatetime

    counter = iter(range(1, 10_000))

    def fake_uuid4() -> uuid.UUID:
        return uuid.uuid5(ID_NAMESPACE, f"id-{next(counter)}")

    fake_uuid = SimpleNamespace(uuid4=fake_uuid4, UUID=uuid.UUID)
    machines_module.uuid = fake_uuid
    history_module.uuid = fake_uuid


def _package_version() -> str:
    """Latest released version from CHANGELOG.md (installed metadata may be stale)."""
    for line in (REPO_ROOT / "CHANGELOG.md").read_text(encoding="utf-8").splitlines():
        match = re.match(r"^## \[(\d+\.\d+\.\d+)\]", line)
        if match:
            return match.group(1)
    return "0.0.0"


def _slim(device: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in device.items() if k not in HISTORY_DROP_FIELDS}


def _write_file(path: Path, content: bytes) -> None:
    """Write a report/CSV with LF endings and no trailing spaces (the repo's pre-commit style)."""
    lines = content.replace(b"\r\n", b"\n").split(b"\n")
    text = b"\n".join(line.rstrip(b" \t") for line in lines).rstrip(b"\n") + b"\n"
    path.write_bytes(text)


def _write_json(name: str, payload: Any) -> int:
    path = OUT_DIR / name
    text = json.dumps(payload, indent=1, sort_keys=False, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8")
    return len(text.encode("utf-8"))


def selftest_status(scan: dict[str, Any], machine_id: str) -> dict[str, Any]:
    """GET /selftests/status as a bench answers it: one row per responding NVMe controller."""
    from cdi_health.classes.nvme_selftest import RESULT_STRINGS, SELF_TEST_CODE_STRINGS

    rows = []
    for device in scan["devices"]:
        dut = str(device.get("dut") or "")
        if not dut.startswith("/dev/nvme") or device.get("grading_status") == "UNGRADED":
            # A dead controller doesn't answer nvme-cli: it is simply not listed.
            continue
        log = device.get("nvme_self_test_log") or {}
        entries = []
        for entry in (log.get("table") or [])[:5]:
            result = int(((entry.get("self_test_result") or {}).get("value")) or 0)
            code = int(((entry.get("self_test_code") or {}).get("value")) or 1)
            entries.append(
                {
                    "result_code": result,
                    "result": RESULT_STRINGS.get(result, f"Reserved ({result})"),
                    "test_type_code": code,
                    "test_type": SELF_TEST_CODE_STRINGS.get(code, f"Unknown ({code})"),
                    "completion_time": int(entry.get("power_on_hours") or 0),
                }
            )
        latest = entries[0] if entries else None
        rows.append(
            {
                "device": dut,
                "supported": True,
                "status": "No self-test in progress",
                "in_progress": False,
                "passed": bool(latest and latest["result_code"] == 0),
                "failed": bool(latest and latest["result_code"] in (5, 6, 7)),
                "aborted": bool(latest and latest["result_code"] in (1, 2, 3, 4, 8, 9)),
                "last_test_date": None,
                "error": None,
                "latest_result": latest,
                "recent_results": entries,
                "current_completion": 0,
                "current_operation": "No self-test in progress",
                "logs_message": None if entries else "No completed self-test entries in NVMe Log Page 0x06.",
            }
        )
    return {"devices": rows, "total": len(rows), "machine_id": machine_id}


def main() -> int:
    os.environ["TZ"] = "UTC"
    time.tzset()
    work = Path(tempfile.mkdtemp(prefix="cdi-demo-"))
    os.environ["CDI_HEALTH_DATA_DIR"] = str(work)
    os.environ["CDI_HEALTH_API_NO_AUTH"] = "1"
    os.environ.pop("CDI_HEALTH_API_TOKEN", None)
    os.environ.pop("CDI_HEALTH_API_MOCK_DATA", None)

    import logging

    logging.disable(logging.WARNING)

    from fastapi.testclient import TestClient

    from cdi_health.api.app import create_app
    from cdi_health.api.schemas import ScanResponse

    _freeze_clock()
    version = _package_version()
    app = create_app()
    runtime = app.state.runtime
    client = TestClient(app)

    try:
        # Register benches the way a check leaves them: reachable, lab (no-auth) mode.
        machine_ids: dict[str, str] = {}
        for bench in BENCHES:
            machine = runtime.machine_store.create_machine(
                {
                    "name": bench["key"],
                    "hostname": bench["hostname"],
                    "address": bench["address"],
                    "location": bench["location"],
                    "notes": bench["notes"],
                }
            )
            machine_ids[bench["key"]] = machine["id"]
            runtime.machine_store.set_status(
                machine["id"],
                "reachable",
                seen=True,
                remote_version=version,
                remote_auth="none",
                remote_hostname=bench["key"],
            )

        # Record scans oldest first, exactly as a forwarded remote scan is stored.
        scans: list[tuple[datetime, dict[str, Any], dict[str, Path]]] = []
        by_key = {bench["key"]: bench for bench in BENCHES}
        for key, days, swaps in EARLIER_SCANS:
            scans.append((LATEST_SCAN_AT[key] - timedelta(days=days), by_key[key], swaps))
        for bench in BENCHES:
            scans.append((LATEST_SCAN_AT[bench["key"]], bench, {}))
        scans.sort(key=lambda item: item[0])

        latest: dict[str, dict[str, Any]] = {}
        for scanned_at, bench, swaps in scans:
            result = grade_bench(bench, scanned_at, swaps)
            machine_id = machine_ids[bench["key"]]
            result = ScanResponse.model_validate(
                {**result, "machine_id": machine_id, "executed_on": "remote", "remote_address": bench["address"]}
            ).model_dump(mode="json")
            runtime.machine_store.record_scan(machine_id, result, success=True)
            runtime.history_store.record_scan(
                {**result, "devices": [_slim(d) for d in result["devices"]]},
                machine_id=machine_id,
                mock=False,
            )
            latest[bench["key"]] = result

        def get(path: str) -> Any:
            response = client.get(path)
            response.raise_for_status()
            return response

        machines = get("/api/v1/machines").json()
        fleet = get("/api/v1/fleet/devices").json()
        history = get("/api/v1/history?limit=500").json()
        history_details = {entry["id"]: get(f"/api/v1/history/{entry['id']}").json() for entry in history}

        # Pre-rendered files: the fleet report and each bench's latest saved
        # scan as a report (HTML + CSV), plus the drive-list CSVs.
        if FILES_DIR.exists():
            shutil.rmtree(FILES_DIR)
        FILES_DIR.mkdir(parents=True)
        latest_history: dict[str, str] = {}
        for entry in history:  # newest first
            latest_history.setdefault(entry["machine_id"], entry["id"])
        report_jobs = [("fleet", {"source": "fleet"})] + [
            (key, {"source": "history", "history_ids": [latest_history[machine_ids[key]]]}) for key in machine_ids
        ]
        report_files: dict[str, dict[str, str]] = {}
        for scope, body in report_jobs:
            for fmt in ("html", "csv"):
                response = client.post(
                    "/api/v1/reports",
                    json={**body, "format": fmt, "output_file": f"cdi-report-demo-{scope}.{fmt}"},
                )
                response.raise_for_status()
                record = response.json()
                content = get(f"/api/v1/reports/{record['filename']}").content
                if fmt == "html":
                    # The demo makes no network requests: drop the web-font import
                    # (the report falls back to its system font stack).
                    content = re.sub(rb"\s*@import url\([^)]*fonts\.googleapis\.com[^)]*\);", b"", content)
                _write_file(FILES_DIR / record["filename"], content)
                report_files.setdefault(machine_ids.get(scope, "fleet"), {})[fmt] = record["filename"]
        # "Recent reports" starts with the fleet report and one bench report.
        shown = {"cdi-report-demo-fleet.html", "cdi-report-demo-fleet.csv", "cdi-report-demo-bench-02.html"}
        reports = [entry for entry in get("/api/v1/reports").json() if entry["filename"] in shown]

        csv_files = {}
        for scope, machine_id in [("all", None)] + [(key, machine_ids[key]) for key in machine_ids]:
            query = f"?machine_id={machine_id}" if machine_id else ""
            response = get(f"/api/v1/fleet/devices.csv{query}")
            match = re.search(r'filename="([^"]+)"', response.headers.get("content-disposition", ""))
            filename = match.group(1) if match else f"cdi-drives-{scope}.csv"
            _write_file(FILES_DIR / filename, response.content)
            csv_files[machine_id or "all"] = filename

        selftests = {machine_ids[key]: selftest_status(scan, machine_ids[key]) for key, scan in latest.items()}

        health = {
            "status": "ok",
            "version": version,
            "hostname": "demo",
            "is_root": True,
            "allow_non_root_mode": False,
            "api_token_enabled": False,
            "auth_mode": "none",
            "missing_required_tools": [],
            "weasyprint_available": False,
            "message": None,
        }

        sizes = {
            "health.json": _write_json("health.json", {"_comment": COMMENT, **health}),
            "machines.json": _write_json("machines.json", {"_comment": COMMENT, "machines": machines}),
            "fleet.json": _write_json("fleet.json", {"_comment": COMMENT, **fleet}),
            "history.json": _write_json(
                "history.json",
                {"_comment": COMMENT, "summaries": history, "details": history_details},
            ),
            "reports.json": _write_json("reports.json", {"_comment": COMMENT, "reports": reports}),
            "selftests.json": _write_json("selftests.json", {"_comment": COMMENT, "benches": selftests}),
            "files.json": _write_json(
                "files.json",
                {
                    "_comment": COMMENT,
                    "generated_at": GENERATED_AT.isoformat(),
                    "drives_csv": csv_files,
                    "reports": report_files,
                },
            ),
        }
    finally:
        shutil.rmtree(work, ignore_errors=True)

    grades: dict[str, int] = {}
    for device in fleet["devices"]:
        grade = str(device.get("health_grade"))
        grades[grade] = grades.get(grade, 0) + 1
    total = sum(sizes.values()) + sum(p.stat().st_size for p in FILES_DIR.iterdir())
    print(f"Wrote demo data to {OUT_DIR.relative_to(REPO_ROOT)} ({total / 1024:.0f} KiB)")
    for name, size in sizes.items():
        print(f"  {name:16} {size / 1024:7.0f} KiB")
    print(f"  files/           {', '.join(sorted(p.name for p in FILES_DIR.iterdir()))}")
    print(f"Grades: {dict(sorted(grades.items()))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
